[package]
name = "sentinel-analytics"
version = "0.1.0"
edition = "2021"

[dependencies]
gstd.workspace = true
sails-rs.workspace = true

[build-dependencies]
sails-idl-gen.workspace = true
sails-rs = { workspace = true, features = ["wasm-builder"] }

[dev-dependencies]
sails-idl-gen.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
